name: sims_ppob_roni_rusmayadi
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  another_flushbar: ^1.12.30
  shimmer: ^3.0.0
  cached_network_image: ^3.2.1
  get_it: ^8.0.1
  http: ^1.2.2
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  intl: ^0.19.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/logos/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
